/*
	Strategy
	Credits: ChimpanG
*/

-----------------------------------------------
-- AiListTypes
-----------------------------------------------

INSERT INTO AiListTypes
		(ListType							)
VALUES 	('LEADER_CVS_KALANGITAN_TECHS'		),
		('LEADER_CVS_KALANGITAN_CIVICS'		),
		('LEADER_CVS_KALANGITAN_DISTRICTS'	),
		('LEADER_CVS_KALANGITAN_BUILDINGS'	),
		('LEADER_CVS_KALANGITAN_PROJECTS'	),
		('LEADER_CVS_KALANGITAN_DIPLOMACY'	),
		('LEADER_CVS_KALANGITAN_UNITS'		),
		('LEADER_CVS_KALANGITAN_TACTICS'	),
		('LEADER_CVS_KALANGITAN_EXPANSION'	),
		('LEADER_CVS_KALANGITAN_PSUEDOS'	);

-----------------------------------------------
-- AiLists
-----------------------------------------------

INSERT INTO AiLists
		(ListType,							AgendaType,					System				)
VALUES  ('LEADER_CVS_KALANGITAN_TECHS',		'AGENDA_CVS_KALANGITAN',	'Technologies'		),
		('LEADER_CVS_KALANGITAN_CIVICS',	'AGENDA_CVS_KALANGITAN',	'Civics'			),
		('LEADER_CVS_KALANGITAN_DISTRICTS',	'AGENDA_CVS_KALANGITAN',	'Districts'			),
		('LEADER_CVS_KALANGITAN_BUILDINGS',	'AGENDA_CVS_KALANGITAN',	'Buildings'			),
		('LEADER_CVS_KALANGITAN_PROJECTS',	'AGENDA_CVS_KALANGITAN',	'Projects'			),
		('LEADER_CVS_KALANGITAN_UNITS',		'AGENDA_CVS_KALANGITAN',	'Units'				),
		('LEADER_CVS_KALANGITAN_TACTICS',	'AGENDA_CVS_KALANGITAN',	'Tactics'			),
		('LEADER_CVS_KALANGITAN_DIPLOMACY',	'AGENDA_CVS_KALANGITAN',	'DiplomaticActions'	),
		('LEADER_CVS_KALANGITAN_EXPANSION',	'AGENDA_CVS_KALANGITAN',	'PlotEvaluations'	),
		('LEADER_CVS_KALANGITAN_PSUEDOS',	'AGENDA_CVS_KALANGITAN',	'PsuedoYields'		);

-----------------------------------------------
-- AiFavoredItems
-----------------------------------------------

INSERT INTO AiFavoredItems
		(ListType,							Item,									Favored	)
VALUES  -- TECHS
		('LEADER_CVS_KALANGITAN_TECHS',		'TECH_CURRENCY',						1		),
		('LEADER_CVS_KALANGITAN_TECHS',		'TECH_SHIPBUILDING',					1		),
		('LEADER_CVS_KALANGITAN_TECHS',		'TECH_CELESTIAL_NAVIGATION',			1		),
		('LEADER_CVS_KALANGITAN_TECHS',		'TECH_CARTOGRAPHY',						1		),
		('LEADER_CVS_KALANGITAN_TECHS',		'TECH_SQUARE_RIGGING',					1		),
		('LEADER_CVS_KALANGITAN_TECHS',		'TECH_BANKING',							1		),
		('LEADER_CVS_KALANGITAN_TECHS',		'TECH_ECONOMICS',						1		),
		('LEADER_CVS_KALANGITAN_TECHS',		'TECH_RADIO',							1		), -- LEADER SPECIFIC
		-- CIVICS
		('LEADER_CVS_KALANGITAN_CIVICS',	'CIVIC_FOREIGN_TRADE',					1		),
		('LEADER_CVS_KALANGITAN_CIVICS',	'CIVIC_EXPLORATION',					1		),
		('LEADER_CVS_KALANGITAN_CIVICS',	'CIVIC_STATE_WORKFORCE',				1		), -- LEADER SPECIFIC
		('LEADER_CVS_KALANGITAN_CIVICS',	'CIVIC_CIVIL_SERVICE',					1		), -- LEADER SPECIFIC
		('LEADER_CVS_KALANGITAN_CIVICS',	'CIVIC_GUILDS',							1		),
		('LEADER_CVS_KALANGITAN_CIVICS',	'CIVIC_FEUDALISM',						1		), -- LEADER SPECIFIC
		-- DISTRICTS
		('LEADER_CVS_KALANGITAN_DISTRICTS',	'DISTRICT_COMMERCIAL_HUB',				1		),
		('LEADER_CVS_KALANGITAN_DISTRICTS',	'DISTRICT_HARBOR',						1		),
		-- BUILDINGS
		('LEADER_CVS_KALANGITAN_BUILDINGS',	'BUILDING_CVS_PHILIPPINES_UI',			1		),
		('LEADER_CVS_KALANGITAN_BUILDINGS',	'BUILDING_BANK',						1		),
		('LEADER_CVS_KALANGITAN_BUILDINGS',	'BUILDING_STOCK_EXCHANGE',				1		),
		('LEADER_CVS_KALANGITAN_BUILDINGS',	'BUILDING_LIGHTHOUSE',					1		),
		('LEADER_CVS_KALANGITAN_BUILDINGS',	'BUILDING_SHIPYARD',					1		),
		('LEADER_CVS_KALANGITAN_BUILDINGS',	'BUILDING_SEAPORT',						1		),
		-- WONDERS
		('LEADER_CVS_KALANGITAN_BUILDINGS',	'BUILDING_BIG_BEN',						1		),
		('LEADER_CVS_KALANGITAN_BUILDINGS',	'BUILDING_COLOSSUS',					1		),
		('LEADER_CVS_KALANGITAN_BUILDINGS',	'BUILDING_EIFFEL_TOWER',				1		),
		('LEADER_CVS_KALANGITAN_BUILDINGS',	'BUILDING_GREAT_LIGHTHOUSE',			1		),
		('LEADER_CVS_KALANGITAN_BUILDINGS',	'BUILDING_GREAT_ZIMBABWE',				1		),
		('LEADER_CVS_KALANGITAN_BUILDINGS',	'BUILDING_VENETIAN_ARSENAL',			1		),
		('LEADER_CVS_KALANGITAN_BUILDINGS',	'BUILDING_PYRAMIDS',					1		), -- LEADER SPECIFIC
		-- PROJECTS
		-- UNITS
		-- TACTICS
		-- DIPLOMACY
		('LEADER_CVS_KALANGITAN_DIPLOMACY',	'DIPLOACTION_PROPOSE_TRADE',			1		),
		('LEADER_CVS_KALANGITAN_DIPLOMACY',	'DIPLOACTION_RESIDENT_EMBASSY',			1		), -- LEADER SPECIFIC
		('LEADER_CVS_KALANGITAN_DIPLOMACY',	'DIPLOACTION_DIPLOMATIC_DELEGATION',	1		), -- LEADER SPECIFIC
		('LEADER_CVS_KALANGITAN_DIPLOMACY',	'DIPLOACTION_DECLARE_FRIENDSHIP',		1		), -- LEADER SPECIFIC
		('LEADER_CVS_KALANGITAN_DIPLOMACY',	'DIPLOACTION_ALLIANCE',					1		); -- LEADER SPECIFIC

INSERT INTO AiFavoredItems
		(ListType,							Item,								Favored,	Value,	StringVal				)
VALUES  -- EXPANSION
		('LEADER_CVS_KALANGITAN_EXPANSION',	'Coastal',							1,			15,		NULL					),
		('LEADER_CVS_KALANGITAN_EXPANSION',	'Resource Class',					1,			5,		'RESOURCECLASS_BONUS'	),
		('LEADER_CVS_KALANGITAN_EXPANSION',	'Resource Class',					1,			10,		'RESOURCECLASS_LUXURY'	),
		('LEADER_CVS_KALANGITAN_EXPANSION',	'New Resources',					1,			15,		NULL					),
		('LEADER_CVS_KALANGITAN_EXPANSION',	'Specific Feature',					1,			5,		'FEATURE_CLIFFS_DOVER'	),
		('LEADER_CVS_KALANGITAN_EXPANSION',	'Specific Feature',					1,			5,		'FEATURE_PIOPIOTAHI'	),
		-- PSUEDOS
		('LEADER_CVS_KALANGITAN_PSUEDOS',	'PSEUDOYIELD_UNIT_TRADE',			1,			5,		NULL					),
		('LEADER_CVS_KALANGITAN_PSUEDOS',	'PSEUDOYIELD_GPP_MERCHANT',			1,			50,		NULL					),
		('LEADER_CVS_KALANGITAN_PSUEDOS',	'PSEUDOYIELD_GPP_ADMIRAL',			1,			30,		NULL					),
		('LEADER_CVS_KALANGITAN_PSUEDOS',	'PSEUDOYIELD_UNIT_NAVAL_COMBAT',	1,			30,		NULL					),
		('LEADER_CVS_KALANGITAN_PSUEDOS',	'PSEUDOYIELD_IMPROVEMENT',			1,			5,		NULL					); -- LEADER SPECIFIC